POST http://localhost:5000/students
Content-Type: application/json
Authorization: Bearer 64123a4d216cd6f972b49e61.58e9be7cfc4b398c5710d2ee.d39281ad305bdb40331accd87478e097

{
    "name": "Tony Tony Chopper",
    "fee": 10000,
    "class_count": 20
}